version: '3.12'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    networks:
      - amazon_network

networks:
  amazon_network:
    driver: bridge